---
- gather_facts: false
  hosts: all
  tasks:
  - yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - epel-release
      - vim
      - git
      - httpd
    become: yes
  - service:
      name: httpd
      state: running
    become: yes
